version: '2'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    expose:
      - "3999"
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    links:
      - 'server'
    ports:
      - "3000-3001:3000-3001"

