export default [
	{
		"language": "Latin",
		"date": "1608-05-29",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0001",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1609-03-12",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0002",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1609-03-16",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0003",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1609-03-20",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0004",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1609-03-26",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0005",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1609-04-10",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0006",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1609-06-11",
		"extra": {},
		"appendices": [],
		"senderLoc": "Antwerpen (be)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Dedel, Johan (1589-1665)",
		"pid": "huyg001/0007",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1610-01?",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0008",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1610-03-04",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Vogelaer, Marcus de (1589-)",
		"pid": "huyg001/0009",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1610-04-16",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0010",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1610-04-28",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "Utrecht (nl)",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Sipenesse, Cornelis van (-1635)",
		"pid": "huyg001/0011",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1610-05",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0012",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1613~",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Dedel, Johan (1589-1665)",
		"pid": "huyg001/0014",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1613~",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Berckel, Clemens van (fl. 1613)",
		"pid": "huyg001/0013",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1615",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "?",
		"pid": "huyg001/0015",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1615~",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "[Amsterdam (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Fagius, Lucas (fl. 1615)",
		"pid": "huyg001/0016",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1616-07",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Leiden (nl)]",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0017",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1616-09-10",
		"extra": {},
		"appendices": [],
		"senderLoc": "Leiden (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "?",
		"pid": "huyg001/0018",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1616-09-29",
		"extra": {},
		"appendices": [],
		"senderLoc": "Leiden (nl)",
		"recipientLoc": "Utrecht (nl)",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Muelen, Andries van der (1591-1654)",
		"pid": "huyg001/x0001",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1616-12-08",
		"extra": {},
		"appendices": [],
		"senderLoc": "Leiden (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0019",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1617-03-12",
		"extra": {},
		"appendices": [],
		"senderLoc": "Leiden (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0020",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1617-03-25",
		"extra": {},
		"appendices": [],
		"senderLoc": "Leiden (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "?",
		"pid": "huyg001/0021",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1617-03-31",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Leiden (nl)]",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Maurits (1595-1642)",
		"pid": "huyg001/0022",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1617-05-19",
		"extra": {},
		"appendices": [],
		"senderLoc": "Leiden (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0023",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1617-06-03",
		"extra": {},
		"appendices": [],
		"senderLoc": "Leiden (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0024",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1617-06-06",
		"extra": {},
		"appendices": [],
		"senderLoc": "Leiden (nl)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Hoefnagel, Susanna (1561-1633)",
		"pid": "huyg001/0025",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1617-06-21",
		"extra": {},
		"appendices": [],
		"senderLoc": "Leiden (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0026",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1617-06-21",
		"extra": {},
		"appendices": [],
		"senderLoc": "Leiden (nl)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Maurits (1595-1642)",
		"pid": "huyg001/0027",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1617-06-26",
		"extra": {},
		"appendices": [],
		"senderLoc": "Leiden (nl)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Maurits (1595-1642)",
		"pid": "huyg001/0028",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1617-06-30",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Leiden (nl)]",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Maurits (1595-1642)",
		"pid": "huyg001/0029",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1617-07-07",
		"extra": {},
		"appendices": [],
		"senderLoc": "Leiden (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0030",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1617-07-08",
		"extra": {},
		"appendices": [],
		"senderLoc": "Leiden (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0031",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1617-07-31",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Leiden (nl)]",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Maurits (1595-1642)",
		"pid": "huyg001/0032",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1617-08-22",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Calandrini, Cesare (1595-1665)",
		"pid": "huyg001/0034",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Italian",
		"date": "1617-08-31",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Calandrini, Cesare (1595-1665)",
		"pid": "huyg001/0036",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1617-09-26?",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Calandrini, Cesare (1595-1665)",
		"pid": "huyg001/0038",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1618-03-18",
		"extra": {},
		"appendices": [],
		"senderLoc": "Zierikzee (nl)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Hoefnagel, Susanna (1561-1633)",
		"pid": "huyg001/0040",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1618-03-25",
		"extra": {},
		"appendices": [],
		"senderLoc": "Zierikzee (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0041",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1618-04-11",
		"extra": {},
		"appendices": [],
		"senderLoc": "Zierikzee (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0043",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1618-04-11",
		"extra": {},
		"appendices": [],
		"senderLoc": "Zierikzee (nl)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Hoefnagel, Susanna (1561-1633)",
		"pid": "huyg001/0042",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1618-06-10",
		"extra": {},
		"appendices": [],
		"senderLoc": "Gravesend (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0044",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1618-06-16",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0045",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1618-06-22",
		"extra": {},
		"appendices": [],
		"senderLoc": "London, Lambeth (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0046",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1618-06-26",
		"extra": {},
		"appendices": [],
		"senderLoc": "London, Lambeth (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0047",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1618-07-01",
		"extra": {},
		"appendices": [],
		"senderLoc": "London, Lambeth (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0048",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1618-07-08",
		"extra": {},
		"appendices": [],
		"senderLoc": "[London, Lambeth (gb)]",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0049",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1618-07-14",
		"extra": {},
		"appendices": [],
		"senderLoc": "London, Lambeth (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0050",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1618-07-14",
		"extra": {},
		"appendices": [],
		"senderLoc": "London, Lambeth (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Maurits (1595-1642)",
		"pid": "huyg001/0051",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1618-07-29",
		"extra": {},
		"appendices": [],
		"senderLoc": "London, Lambeth (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0052",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1618-08-12",
		"extra": {},
		"appendices": [],
		"senderLoc": "London, Lambeth (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0053",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1618-08-16",
		"extra": {},
		"appendices": [],
		"senderLoc": "London, Lambeth (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0054",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1618-08-31",
		"extra": {},
		"appendices": [],
		"senderLoc": "London, Lambeth (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0055",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1618-09-17",
		"extra": {},
		"appendices": [],
		"senderLoc": "London, Lambeth (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0056",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1618-09-28",
		"extra": {},
		"appendices": [],
		"senderLoc": "London, Lambeth (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0057",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1618-10-06",
		"extra": {},
		"appendices": [],
		"senderLoc": "London, Lambeth (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0058",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1619",
		"extra": {},
		"appendices": [],
		"senderLoc": "?",
		"recipientLoc": "[Amsterdam (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Roemers Visscher, Anna (1583-1651)",
		"pid": "huyg001/x0002",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1619-01-08",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Utrecht (nl)]",
		"recipientLoc": "[Utrecht (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0059",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1619-01-20",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Utrecht (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Hilten, Anthonie van (-1670)",
		"pid": "huyg001/0061",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1619-03-30",
		"extra": {},
		"appendices": [],
		"senderLoc": "Utrecht (nl)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0063",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1619-07-11",
		"extra": {},
		"appendices": [],
		"senderLoc": "Kampen (nl)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0065",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1619-09-05",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Paris (fr)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Bertius, Petrus (1565-1629)",
		"pid": "huyg001/0068",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1619-09-07",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0069",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1619-09-30?",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "[Antwerpen (be)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Uytenbogaert, Johannes (1557-1644)",
		"pid": "huyg001/0070",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1619-09-30?",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "[Middelburg (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Cats, Jacob (1577-1660)",
		"pid": "huyg001/0071",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1619-10-21",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0073",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1619-10-28",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0074",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1620-02-11",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0075",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1620-04-13",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0076",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1620-05-01",
		"extra": {},
		"appendices": [],
		"senderLoc": "Köln (de)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0078",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1620-05-07",
		"extra": {},
		"appendices": [],
		"senderLoc": "Frankfurt am Main (de)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0079",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1620-05-18",
		"extra": {},
		"appendices": [],
		"senderLoc": "Stuttgart (de)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Dorp, Dorothée van (1593-1657)",
		"pid": "huyg001/0080",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1620-05-19",
		"extra": {},
		"appendices": [],
		"senderLoc": "Stuttgart (de)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0081",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1620-06-11",
		"extra": {},
		"appendices": [],
		"senderLoc": "Vicenza (it)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0082",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1620-06-18",
		"extra": {},
		"appendices": [],
		"senderLoc": "Venezia (it)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0083",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1620-06-18",
		"extra": {},
		"appendices": [],
		"senderLoc": "Venezia (it)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Dorp, Dorothée van (1593-1657)",
		"pid": "huyg001/0084",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1620-06-25",
		"extra": {},
		"appendices": [],
		"senderLoc": "Venezia (it)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0085",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1620-07-02",
		"extra": {},
		"appendices": [],
		"senderLoc": "Venezia (it)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0086",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1620-07-02",
		"extra": {},
		"appendices": [],
		"senderLoc": "Venezia (it)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0087",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1620-07-04",
		"extra": {},
		"appendices": [],
		"senderLoc": "Venezia (it)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0088",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1620-08-13",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0089",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1620-08-24",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0090",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1620-10-01",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0092",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1620-10-08",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0093",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1620-10-26",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0094",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1621-02-02",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0097",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1621-02-14",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0098",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1621-02-15",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0099",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1621-02-23",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0100",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "?",
		"date": "1621-03-03",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0101",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1621-03-10",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0102",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1621-03-13",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0103",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1621-03-18",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0104",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1621-03-29",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0105",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1621-05-14",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0107",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1621-06-06",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0108",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1621-09-23",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0109",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1621-10-12",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0110",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1621-10-19",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Valtellina (it)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Sprecher von Bernegg, Fortunatus (1585-1647)",
		"pid": "huyg001/0111",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1621-11-24",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Middelburg (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Cats, Jacob (1577-1660)",
		"pid": "huyg001/0112",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1621-12-07",
		"extra": {},
		"appendices": [],
		"senderLoc": "Gravesend (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0113",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1621-12-18",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0115",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1621-12-20",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Suriano, Cristoforo (1580-)",
		"pid": "huyg001/0116",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1621-12-26",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0118",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1621-12-29",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0119",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-01-03",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0120",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1622-01-09",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0121",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1622-01-18",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0122",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1622-01-27",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0123",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1622-02-04",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0125",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1622-02-10",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Maurits (1595-1642)",
		"pid": "huyg001/0126",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-02-11",
		"extra": {},
		"appendices": [],
		"senderLoc": "[London (gb)]",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0129",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1622-02-20",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Middelburg (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Cats, Jacob (1577-1660)",
		"pid": "huyg001/0131",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-02-21",
		"extra": {},
		"appendices": [],
		"senderLoc": "[London (gb)]",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0130",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1622-03",
		"extra": {},
		"appendices": [],
		"senderLoc": "[London (gb)]",
		"recipientLoc": "[?]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Maurits (1595-1642)",
		"pid": "huyg001/0137",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-03-07",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0132",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-03-17",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0138",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1622-03-22",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Middelburg (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Cats, Jacob (1577-1660)",
		"pid": "huyg001/0140",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "?",
		"date": "1622-03-30",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0141",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-04-08",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0142",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "?",
		"date": "1622-04-13",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0143",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1622-04-23",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0144",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1622-04-27",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Hoefnagel, Susanna (1561-1633)",
		"pid": "huyg001/0145",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1622-04-30",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0147",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1622-05-08",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Middelburg (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Cats, Jacob (1577-1660)",
		"pid": "huyg001/0148",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1622-05-10",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0149",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1622-05-21",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0152",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1622-05-29",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0153",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-06-08",
		"extra": {},
		"appendices": [],
		"senderLoc": "[London (gb)]",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0155",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1622-06-12",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0157",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1622-06-23",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0158",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-06-28",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0159",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1622-07-03",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0160",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-07-25",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0164",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1622-07-28",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Middelburg (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Cats, Jacob (1577-1660)",
		"pid": "huyg001/0165",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1622-07-28",
		"extra": {},
		"appendices": [],
		"senderLoc": "[London (gb)]",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Suriano, Cristoforo (1580-)",
		"pid": "huyg001/0166",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-08-10",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0169",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "?",
		"date": "1622-08-14",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0170",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-08-14?",
		"extra": {},
		"appendices": [],
		"senderLoc": "[London (gb)]",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0171",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-08-27",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0173",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-09-03",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0175",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-09-11",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Dorp, Dorothée van (1593-1657)",
		"pid": "huyg001/0177",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-09-12",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0178",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1622-09-17",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0179",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-09-19",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0181",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-09-27",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0182",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-10-09",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0185",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-10-14",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0186",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-10-17",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0189",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1622-10-18",
		"extra": {},
		"appendices": [],
		"senderLoc": "[London (gb)]",
		"recipientLoc": "[London (gb)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Jonson, Ben (1572-1637)",
		"pid": "huyg001/0190",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-11-04",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0193",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1622-11-10",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Huygens, Christiaan (1551-1624)",
		"pid": "huyg001/0194",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "?",
		"date": "1622-12-25",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0198",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "?",
		"date": "1623-03-02",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0201",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1623-04",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Cecil, Edward (1572-1638)",
		"pid": "huyg001/0203",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1623-04-22",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Dordrecht (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Cats, Jacob (1577-1660)",
		"pid": "huyg001/0202",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1623-07-08",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[London (gb)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Brouart, Joannes (1584-)",
		"pid": "huyg001/0205",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1623-09-29",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "?",
		"pid": "huyg001/0206",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1623-10-30",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Dordrecht (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Cats, Jacob (1577-1660)",
		"pid": "huyg001/0208",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1623-11-02",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "London (gb)",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Thorius, Raphael (1560-1625)",
		"pid": "huyg001/0209",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1623-11-08",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "[Dordrecht (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Cats, Jacob (1577-1660)",
		"pid": "huyg001/0211",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1624-01-27",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0213",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1624-02-13",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0214",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1624-05-24",
		"extra": {},
		"appendices": [],
		"senderLoc": "London (gb)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0240",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1624-10-30",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Muiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Hooft, Pieter Cornelisz. (1581-1647)",
		"pid": "huyg001/0250",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1625-02-28",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "[London (gb)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Thorius, Raphael (1560-1625)",
		"pid": "huyg001/0254",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1625-04",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Hooft, Pieter Cornelisz. (1581-1647)",
		"pid": "huyg001/0257",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1625-04",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Burgh, Jacob van der (1599-1659)",
		"pid": "huyg001/0258",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1625-05-11",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Burgh, Jacob van der (1599-1659)",
		"pid": "huyg001/0265",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1625-05-11",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Barlaeus, Caspar (1584-1648)",
		"pid": "huyg001/0266",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1625-05-27",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Heinsius, Daniël (1580-1655)",
		"pid": "huyg001/0268",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1625-06",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "[Waalwijk (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Nassau, Frederik Hendrik van (1584-1647)",
		"pid": "huyg001/0269",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Italian",
		"date": "1625-07-17",
		"extra": {},
		"appendices": [],
		"senderLoc": "Waalwijk (nl)",
		"recipientLoc": "[Amsterdam (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Reael, Laurens Laurensz. (1583-1637)",
		"pid": "huyg001/0273",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1625-08-18",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[London (gb)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Thorius, Raphael (1560-1625)",
		"pid": "huyg001/0280",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1625-08-20",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "[Middelburg (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Boreel, Johan (1577-1629)",
		"pid": "huyg001/0281",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1625-08-27",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "[Middelburg (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Boreel, Johan (1577-1629)",
		"pid": "huyg001/0283",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1625-09-12",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "[London (gb)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Aerssen, François van (1572-1641)",
		"pid": "huyg001/0285",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1625-09-21",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Burgh, Jacob van der (1599-1659)",
		"pid": "huyg001/0288",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1625-09-26",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Barlaeus, Caspar (1584-1648)",
		"pid": "huyg001/0289",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1625-11-27",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Barlaeus, Caspar (1584-1648)",
		"pid": "huyg001/0296",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1625-12",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Barlaeus, Caspar (1584-1648)",
		"pid": "huyg001/0299",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1626-01-31",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Hooft, Pieter Cornelisz. (1581-1647)",
		"pid": "huyg001/0304",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1626-03-17",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Amsterdam (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Hooft, Pieter Cornelisz. (1581-1647)",
		"pid": "huyg001/0308",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1626-04-11",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Dorp, Dorothée van (1593-1657)",
		"pid": "huyg001/0310",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1626-04-11",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Dorp, Dorothée van (1593-1657)",
		"pid": "huyg001/0311",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1626-05",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Barlaeus, Caspar (1584-1648)",
		"pid": "huyg001/0317",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1626-05-30",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[London (gb)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Oldisworth, Michael (1591-1654)",
		"pid": "huyg001/0319",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1626-07-20",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Nassau, Frederik Hendrik van (1584-1647)",
		"pid": "huyg001/0321",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1626-07-27",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Nassau, Frederik Hendrik van (1584-1647)",
		"pid": "huyg001/0322",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1626-08-06",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Amsterdam (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Hooft, Pieter Cornelisz. (1581-1647)",
		"pid": "huyg001/0324",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1626-08-08",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Amsterdam (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Hooft, Pieter Cornelisz. (1581-1647)",
		"pid": "huyg001/0326",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1626-09-09",
		"extra": {},
		"appendices": [],
		"senderLoc": "Amsterdam (nl)",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Nassau, Frederik Hendrik van (1584-1647)",
		"pid": "huyg001/0329",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Latin",
		"date": "1626-12-18",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Barlaeus, Caspar (1584-1648)",
		"pid": "huyg001/0333",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "French",
		"date": "1627-03-02",
		"extra": {},
		"appendices": [],
		"senderLoc": "Amsterdam (nl)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Dorp, Dorothée van (1593-1657)",
		"pid": "huyg001/0342",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1627-03-15",
		"extra": {},
		"appendices": [],
		"senderLoc": "[Den Haag (nl)]",
		"recipientLoc": "?",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Noot, Louise van der (fl. 1627-1632)",
		"pid": "huyg001/0346",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1627-05-15",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[London (gb)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Oldisworth, Michael (1591-1654)",
		"pid": "huyg001/0353",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1627-06-04",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Barlaeus, Caspar (1584-1648)",
		"pid": "huyg001/0355",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1627-06-25",
		"extra": {},
		"appendices": [],
		"senderLoc": "Den Haag (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Barlaeus, Caspar (1584-1648)",
		"pid": "huyg001/0356",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1627-07-15",
		"extra": {},
		"appendices": [],
		"senderLoc": "Emmerich (de)",
		"recipientLoc": "[Den Haag (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Solms-Braunfels, Amalia van (1602-1675)",
		"pid": "huyg001/0360",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1627-07-25",
		"extra": {},
		"appendices": [],
		"senderLoc": "Groenlo (nl)",
		"recipientLoc": "[London (gb)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Oldisworth, Michael (1591-1654)",
		"pid": "huyg001/0361",
		"appendixOf": null,
		"extraFields": []
	},
	{
		"language": "Dutch",
		"date": "1627-07-31",
		"extra": {},
		"appendices": [],
		"senderLoc": "Groenlo (nl)",
		"recipientLoc": "[Leiden (nl)]",
		"sender": "Huygens, Constantijn (1596-1687)",
		"recipient": "Barlaeus, Caspar (1584-1648)",
		"pid": "huyg001/0362",
		"appendixOf": null,
		"extraFields": []
	}
];