FROM nginx:1.11.8-alpine

COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY build /usr/share/nginx/html/build/
COPY index.html /usr/share/nginx/html/index.html

COPY node_modules/react /usr/share/nginx/html/node_modules/react/
COPY node_modules/react-dom /usr/share/nginx/html/node_modules/react-dom/
COPY node_modules/hire-forms-input /usr/share/nginx/html/node_modules/hire-forms-input/
COPY node_modules/hire-forms-select /usr/share/nginx/html/node_modules/hire-forms-select/

EXPOSE 80
